<template>
  <div class="LogView">
    <div class="log-header">
      <div class="icon-type"><img :src="getIcon" alt="" /></div>

      <div class="log-header-column">
        <div class="log-title">{{ title }}</div>
        <div class="log-date">
          Last updated: {{ parseDate }} <span v-if="isToday">(Today)</span>
        </div>
      </div>

      <button v-if="log.type != 'UNLINK'" @click="undo">UNDO</button>
    </div>
    <div class="log-body">
      <div class="timeline" />
      <div class="log-container">
        {{ log.type_ }}
        {{ log.rule }}
        {{ log.monitor }}
        {{ log.destination }}
        <!-- <Table :log="log" /> -->
      </div>
    </div>
  </div>
</template>

<script>
import anime from "animejs";
export default {
  props: ["log", "title", "index"],
  //   components: { Table },
  computed: {
    getIcon() {
      // console.log(this.log);
      let icon = null;
      if (this.log.type_ == "MOVE")
        icon = require("../../assets/images/move.svg");
      else if (this.log.type_ == "COPY")
        icon = require("../../assets/images/copy.svg");
      else if (this.log.type_ == "DELETE")
        icon = require("../../assets/images/delete.svg");
      else if (this.log.type_ == "UNLINK")
        icon = require("../../assets/images/unlink.svg");

      // console.log(icon);
      return icon;
    },
    parseDate() {
      // datetime generated by crate - chrono
      const date = new Date(this.log.timestamp);
      console.log("date converted: ", date);
      console.log("getFullYear(): ", date.getFullYear());

      const year = date?.getFullYear();
      const month = date.getMonth() + 1;
      const day = date.getDate();

      console.log(date.getDate());
      console.log(`${day}/${month}/${year}`);

      return `${day}/${month}/${year}`;
    },
    isToday() {
      const date = new Date(this.log.timestamp);
      const year = date?.getFullYear();
      const month = date.getMonth();
      const day = date.getDate();

      const dateNow = new Date();

      if (
        dateNow.getMonth() + 1 == month + 1 &&
        dateNow?.getFullYear() == year &&
        dateNow.getDate() == day
      )
        return true;
      return false;
    },
  },
  methods: {
    undo() {
      anime({
        targets: this.$el,
        height: "0",
        duration: 100,
        easing: "easeInOutQuad",
      });
      setTimeout(() => {
        this.$store.commit("removeLog", this.index.split(""));
      }, 100);
    },
  },
  mounted() {
    // console.log(this.index);
    let duration = this.index * (1000 / this.index);
    if (this.index == "00") duration = 800;
    anime({
      targets: this.$el,
      opacity: 1,
      height: "125px",
      duration: duration,
      // easing: "easeInOutQuad",
    });
  },
};
</script>

<style lang="scss" scoped>
button {
  background: $darkbg;
  outline: none;
  padding: 9px;
  border: none;
  font-family: Comfortaa;
  border-radius: 3px;
  color: white;
  position: absolute;
  top: 0px;
  right: 15px;
}

#LogView {
  opacity: 0;
  // background: red;
  height: 0px;
  overflow: hidden;
  font-family: Comfortaa;
  // margin-bottom: 15px;
}

.log-header {
  display: flex;
  position: relative;
  align-items: center;
}

.log-header-column {
  display: flex;
  flex-flow: column nowrap;
  /* background: blue; */
  align-items: flex-start;
}

.icon-type {
  background: #c4c4c4;

  border-radius: 50%;
  padding: 5px 5px 5px 6px;
  width: 38px;
  height: 38px;
  display: flex;
  justify-content: center;
  align-items: center;
  margin-right: 10px;
}

.log-title {
  color: #d7d7d7;
}

.log-date {
  color: #7a7a7a;
  margin-top: 4px;
  font-size: 13px;
}

.icon-type img {
  height: 28px;
}

.log-body {
  height: 80px;
  /* background: var(--darkPrimary); */
  position: relative;
}

.timeline {
  height: calc(100%);
  position: absolute;
  width: 3px;
  background: #4e4e4e;
  border-radius: 3px;
  left: 22px;
  bottom: -7px;
}

.log-container {
  background: $darkbg;
  height: 100%;
  width: calc(100% - 50px);
  position: absolute;
  color: white;
  right: 0px;
}
</style>