//@ts-nocheck
export const Logs: ILog[] = [
  {
    id: "1",
    name: "Listener 1",
    path: "/path/to/file1",
    action: "MOVE",
    parentId: "parent1",
    timestamp: "2023-06-01T10:00:00Z",
    destination: "/path/to/destination1",
    message: "log message 1",
    level: "WARN",
  },
  {
    id: "2",
    name: "Listener 2",
    path: "/path/to/file2",
    action: "COPY",
    parentId: "parent2",
    timestamp: "2023-06-01T11:00:00Z",
    destination: "/path/to/destination2",
    message: "log message 2",
    level: "SUCCESS",
  },
  {
    id: "3",
    name: "Listener 1",
    path: "/path/to/file3",
    action: "UNLINK",
    parentId: "parent3",
    timestamp: "2023-06-01T12:00:00Z",
    destination: "/path/to/destination3",
    message: "log message 3",
    level: "INFO",
  },
  // {
  //   id: "4",
  //   path: "/path/to/file4",
  //   action: "DELETE",
  //   parentId: "parent4",
  //   timestamp: "2023-06-01T13:00:00Z",
  //   destination: "/path/to/destination4",
  //   message: "error:log message 4",
  // },
  // {
  //   id: "5",
  //   path: "/path/to/file5",
  //   action: "RENAME",
  //   parentId: "parent5",
  //   timestamp: "2023-06-01T14:00:00Z",
  //   destination: "/path/to/destination5",
  //   message: "warn:log message 5",
  // },
  // {
  //   id: "6",
  //   path: "/path/to/file6",
  //   action: "COPY",
  //   parentId: "parent6",
  //   timestamp: "2023-06-01T15:00:00Z",
  //   destination: "/path/to/destination6",
  //   message: "error:log message 6",
  // },
  // {
  //   id: "7",
  //   path: "/path/to/file7",
  //   action: "MOVE",
  //   parentId: "parent7",
  //   timestamp: "2023-06-01T16:00:00Z",
  //   destination: "/path/to/destination7",
  //   message: "success:log message 7",
  // },
  // {
  //   id: "8",
  //   path: "/path/to/file8",
  //   action: "DELETE",
  //   parentId: "parent8",
  //   timestamp: "2023-06-01T17:00:00Z",
  //   destination: "/path/to/destination8",
  //   message: "warn:log message 8",
  // },
  // {
  //   id: "9",
  //   path: "/path/to/file9",
  //   action: "RENAME",
  //   parentId: "parent9",
  //   timestamp: "2023-06-01T18:00:00Z",
  //   destination: "/path/to/destination9",
  //   message: "error:log message 9",
  // },
  // {
  //   id: "10",
  //   path: "/path/to/file10",
  //   action: "UNLINK",
  //   parentId: "parent10",
  //   timestamp: "2023-06-01T19:00:00Z",
  //   destination: "/path/to/destination10",
  //   message: "success:log message 10",
  // },
  // {
  //   id: "11",
  //   path: "/path/to/file11",
  //   action: "COPY",
  //   parentId: "parent11",
  //   timestamp: "2023-06-01T20:00:00Z",
  //   destination: "/path/to/destination11",
  //   message: "warn:log message 11",
  // },
  // {
  //   id: "12",
  //   path: "/path/to/file12",
  //   action: "MOVE",
  //   parentId: "parent12",
  //   timestamp: "2023-06-01T21:00:00Z",
  //   destination: "/path/to/destination12",
  //   message: "Log message 12",
  // },
  // {
  //   id: "13",
  //   path: "/path/to/file13",
  //   action: "RENAME",
  //   parentId: "parent13",
  //   timestamp: "2023-06-01T22:00:00Z",
  //   destination: "/path/to/destination13",
  //   message: "error:log message 13",
  // },
  // {
  //   id: "14",
  //   path: "/path/to/file14",
  //   action: "MOVE",
  //   parentId: "parent14",
  //   timestamp: "2023-06-01T23:00:00Z",
  //   destination: "/path/to/destination14",
  //   message: "warn:log message 14",
  // },
  // {
  //   id: "15",
  //   path: "/path/to/file15",
  //   action: "COPY",
  //   parentId: "parent15",
  //   timestamp: "2023-06-02T00:00:00Z",
  //   destination: "/path/to/destination15",
  //   message: "success:log message 15",
  // },
];

export const Listeners: IListener[] = [
  {
    id: "parent1",
    deep: true,
    title: "Listener 1",
    enabled: true,
    monitors: [],
    selection: "Any",
    rules: [
      {
        condition: "Includes",
        search: "FileName",
        data: {
          size: [0, "B"],
          text: ["py", "rs"],
        },
      },
    ],
    actions: [
      {
        action: "MOVE" as TActionOpts,
        path: "/path/to/destination1",
      },
    ],
  },
  {
    id: "parent2",
    deep: true,
    title: "Listener 2",
    enabled: true,
    monitors: [],
    selection: "Any",
    rules: [],
    actions: [
      {
        action: "MOVE",
        path: "/path/to/destination2",
      },
    ],
  },
  {
    id: "parent3",
    deep: true,
    title: "Listener 3",
    enabled: true,
    monitors: [],
    selection: "Any",
    rules: [],
    actions: [
      {
        action: "MOVE",
        path: "/path/to/destination2",
      },
    ],
  },
  {
    id: "parent4",
    deep: true,
    title: "Listener 4",
    enabled: true,
    monitors: [],
    selection: "Any",
    rules: [],
    actions: [
      {
        action: "MOVE",
        path: "/path/to/destination2",
      },
    ],
  },
  {
    id: "parent5",
    deep: true,
    title: "Listener 5",
    enabled: true,
    monitors: [],
    selection: "Any",
    rules: [],
    actions: [
      {
        action: "MOVE",
        path: "/path/to/destination2",
      },
    ],
  },
  {
    id: "parent6",
    deep: true,
    title: "Listener 6",
    enabled: true,
    monitors: [],
    selection: "Any",
    rules: [],
    actions: [
      {
        action: "MOVE",
        path: "/path/to/destination2",
      },
    ],
  },
  {
    id: "parent7",
    deep: true,
    title: "Listener 7",
    enabled: true,
    monitors: [],
    selection: "Any",
    rules: [],
    actions: [
      {
        action: "MOVE",
        path: "/path/to/destination2",
      },
    ],
  },
  {
    id: "parent8",
    deep: true,
    title: "Listener 8",
    enabled: true,
    monitors: [],
    selection: "Any",
    rules: [],
    actions: [
      {
        action: "MOVE",
        path: "/path/to/destination2",
      },
    ],
  },
  {
    id: "parent9",
    deep: true,
    title: "Listener 9",
    enabled: true,
    monitors: [],
    selection: "Any",
    rules: [],
    actions: [
      {
        action: "MOVE",
        path: "/path/to/destination2",
      },
    ],
  },
  {
    id: "parent10",
    deep: true,
    title: "Listener 10",
    enabled: true,
    monitors: [],
    selection: "Any",
    rules: [],
    actions: [
      {
        action: "MOVE",
        path: "/path/to/destination2",
      },
    ],
  },
  {
    id: "parent11",
    deep: true,
    title: "Listener 11",
    enabled: true,
    monitors: [],
    selection: "Any",
    rules: [],
    actions: [
      {
        action: "MOVE",
        path: "/path/to/destination2",
      },
    ],
  },
  {
    id: "parent12",
    deep: true,
    title: "Listener 12",
    enabled: true,
    monitors: [],
    selection: "Any",
    rules: [],
    actions: [
      {
        action: "MOVE",
        path: "/path/to/destination2",
      },
    ],
  },
  {
    id: "parent13",
    deep: true,
    title: "Listener 13",
    enabled: true,
    monitors: ["/path/to/file13"],
    selection: "Any",
    rules: [],
    actions: [
      {
        action: "MOVE",
        path: "/path/to/destination2",
      },
    ],
  },
  {
    id: "parent14",
    deep: true,
    title: "Listener 14",
    enabled: true,
    monitors: [],
    selection: "Any",
    rules: [],
    actions: [
      {
        action: "MOVE",
        path: "/path/to/destination2",
      },
    ],
  },
  {
    id: "parent15",
    deep: true,
    title: "Listener 15",
    enabled: true,
    monitors: ["/path/to/file15"],
    selection: "Any",
    rules: [],
    actions: [
      {
        action: "MOVE",
        path: "/path/to/destination2",
      },
    ],
  },
];
